version: '3'
services:
 
  app:
    container_name: app
    image: golang:1.21.4
    depends_on:
       - postgres
       - migrate
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/app/
    working_dir: /app
    command: >
      bash -c "go test internal/test/javacode_test.go"    
    
     
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./../db:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U user -d postgres
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 60s
   
  migrate:
    container_name: migrate
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://user:password@postgres:5432/postgres?sslmode=disable",
        "up"
      ]
    depends_on:
       - postgres
    